name: untitled
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

#--------PACKAGES--------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  connectivity_plus: ^5.0.2
  lottie: ^3.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

  #Dependencies added by Dilshad.
  shared_preferences: ^2.0.13
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  iconsax_flutter: ^1.0.0
  carousel_slider: ^5.0.0

  # product specific
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # Firebase dependencies:
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  google_sign_in: ^6.2.2
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true




  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/content/
    - assets/images/reviews/
    - assets/images/user/


  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins,Sedan_SC/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins,Sedan_SC/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins,Sedan_SC/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins,Sedan_SC/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins,Sedan_SC/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins,Sedan_SC/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins,Sedan_SC/Poppins/Poppins-Bold.ttf
          weight: 800