// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:843827003458:web:1d7bafdab0519661832ddb',
    messagingSenderId: '843827003458',
    projectId: 'devault-a4416',
    authDomain: 'devault-a4416.firebaseapp.com',
    storageBucket: 'devault-a4416.firebasestorage.app',
    measurementId: 'G-EB63XD8W1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:843827003458:android:8203a79af15b382c832ddb',
    messagingSenderId: '843827003458',
    projectId: 'devault-a4416',
    storageBucket: 'devault-a4416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:843827003458:ios:d506bc6cee0e2555832ddb',
    messagingSenderId: '843827003458',
    projectId: 'devault-a4416',
    storageBucket: 'devault-a4416.firebasestorage.app',
    iosClientId: '843827003458-2dne500ie8rrg41vgmoefqsjqhgtkf21.apps.googleusercontent.com',
    iosBundleId: 'com.example.devault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:142868810327:web:72fc6b8acd3e4d778e3112',
    messagingSenderId: '142868810327',
    projectId: 'devault-ecom',
    authDomain: 'devault-ecom.firebaseapp.com',
    storageBucket: 'devault-ecom.firebasestorage.app',
    measurementId: 'G-QL5RKFWHC8',
  );

}
