// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD-9PQI9BlI2KXJRSvcwTYdttPBziLqa0',
    appId: '1:142868810327:web:97b850d053171c8d8e3112',
    messagingSenderId: '142868810327',
    projectId: 'devault-ecom',
    authDomain: 'devault-ecom.firebaseapp.com',
    storageBucket: 'devault-ecom.firebasestorage.app',
    measurementId: 'G-DKS1TQS4YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDybraeU9dNjPDxU9ka_-71SObSNY5q590',
    appId: '1:142868810327:android:4bbb643c68108c7c8e3112',
    messagingSenderId: '142868810327',
    projectId: 'devault-ecom',
    storageBucket: 'devault-ecom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFpNdo_prNxnFXTD5N56jCoT_lnhCwCg8',
    appId: '1:142868810327:ios:9f4643e2d92779618e3112',
    messagingSenderId: '142868810327',
    projectId: 'devault-ecom',
    storageBucket: 'devault-ecom.firebasestorage.app',
    androidClientId: '142868810327-9fkc5pim31ked7surrrggronfg0fqegt.apps.googleusercontent.com',
    iosClientId: '142868810327-d71efmea073ihurbo3b5d471to4rbssg.apps.googleusercontent.com',
    iosBundleId: 'com.example.devault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD-9PQI9BlI2KXJRSvcwTYdttPBziLqa0',
    appId: '1:142868810327:web:72fc6b8acd3e4d778e3112',
    messagingSenderId: '142868810327',
    projectId: 'devault-ecom',
    authDomain: 'devault-ecom.firebaseapp.com',
    storageBucket: 'devault-ecom.firebasestorage.app',
    measurementId: 'G-QL5RKFWHC8',
  );

}